title: Rafael Collado
author: rafaelcolladojr
subtitle: The life of a vagabond engineer

url: "https://rafaelcollado.com"
baseurl: ""

# profile-picture: assets/profile.png
# favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/

highlighter: rouge

navbar:
  - name: "Home"
    link: "/"
  - name: "Articles"
    link: "/articles/"
  - name: "Projects"
    link: "/projects/"
  - name: "Resume"
    link: "/assets/r_collado_resume.pdf"

# Footer 
footer_text: "Yes"
footer_only_homepage: true

github: "https://github.com/rafaelcolladojr"
x: "https://x.com/rafaelcolladojr"
instagram: "https://instagram.com/rafaelcolladojr"
